version: '3.8'
services: 
  laravel:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host="0.0.0.0"'
    volumes:
      - .:/app
      - /app/vendor
      - /app/node_modules
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on: 
      - mysql

  queue:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    depends_on: 
      - mysql        

  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    env_file:
      - ./.env
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 3306:3306
