-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Servidor: localhost:3306
-- Tiempo de generación: 04-02-2020 a las 08:08:14
-- Versión del servidor: 5.6.41-84.1
-- Versión de PHP: 7.2.7

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `josedan1_OGM`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `questions`
--

CREATE TABLE `questions` (
  `id` int(10) UNSIGNED NOT NULL,
  `question` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `answer` text COLLATE utf8mb4_unicode_ci,
  `asked_by` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_faq` tinyint(1) NOT NULL DEFAULT '0',
  `answered_by` int(10) UNSIGNED DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Volcado de datos para la tabla `questions`
--

INSERT INTO `questions` (`id`, `question`, `answer`, `asked_by`, `is_faq`, `answered_by`, `created_at`, `updated_at`) VALUES
(1, '¿Qué es un Organismo Genéticamente Modificado?', 'Un organismo genéticamente modificado (OGM) es un ser vivo (planta, animal, hongo o bacteria) al que se le ha modificado uno o varios genes, por medio de técnicas de ingeniería genética (ArgenBio, 2007).', 'admin@mail.com', 1, 1, '2020-01-20 18:46:46', '2020-01-20 19:49:27'),
(2, '¿Qué es un gen?', 'El gen es la unidad física básica de la herencia, que contienen la información necesaria para precisar los rasgos transmisibles de padres a hijos. Los genes le indican al organismo cómo producir proteínas específicas, determinando las partes del cuerpo y sus funciones (NIH, s.f.; Medline, 2017).\nLos genes están dispuestos, en estructuras llamadas cromosomas, que contienen moléculas de ADN (ácido desoxiribonucléico). Los seres humanos tienen alrededor de 20.000 genes organizados en 46 cromosomas (NIH, s.f.). Muchas características personales, como la estatura, dependen de la combinación de varios genes, mientras que otros rasgos, como ciertas enfermedades, dependen de un solo gen. La composición genética de un individuo se llama genotipo (Medline, 2017).', 'admin@mail.com', 1, 1, '2020-01-20 18:47:12', '2020-01-20 18:52:27'),
(3, '¿Qué es el ADN?', 'El ADN es una molécula que contiene las instrucciones biológicas codificadoras de la información celular de cada ser vivo, necesarias para desarrollarse, sobrevivir y reproducirse, y que se transmiten de los organismos adultos a su descendencia durante la reproducción (NIH, 2015). \nEl ADN se almacena generalmente en los núcleos de las células, y se conforma de unas sustancias químicas básicas llamadas nucleótidos (adenina, guanina, timina y citosina) que se unen formando cadenas, lo que le da al ADN su característica forma de espiral de doble hélice (NIH, 2015; ArgenBio, 2007).', 'admin@mail.com', 1, 1, '2020-01-20 18:47:57', '2020-01-20 19:26:58'),
(4, '¿Qué es el proyecto genoma humano?', 'Un genoma es una colección completa de ácido desoxirribonucleico (ADN) de un organismo, que contiene la totalidad del material genético que posee un individuo o una especie en particular (RAE, 2018).\nEl proyecto genoma, fue un esfuerzo internacional conjunto, de aproximadamente 13 años de duración, para desarrolla un mapa de la totalidad de los genes humanos (NIH, 2016), con la colaboración de USA, Inglaterra, Japón, Francia, Alemania, China y otros países. \nEntre sus objetivos estuvo: identificar los cerca de 20.500 genes en el ADN humano, determinar las secuencia de los 3 billones de pares de bases que lo conforman, registrar dicha información en bases de datos con herramientas de análisis mejoradas y manejar las implicaciones éticas, legales, económicas y sociales que de dicho proyecto se derivaran (HGP, 2017).', 'admin@mail.com', 1, 1, '2020-01-20 18:48:23', '2020-01-20 18:52:32'),
(5, '¿Qué es la biotecnología?', 'La biotecnología consiste en el uso de tecnologías para manipular sistemas biológicos y organismos vivos o sus derivados, para la creación o modificación de productos y procesos, según explica el Convenio sobre la Diversidad Biológica -CBD (1992).\nA partir del CDB, se desarrolló en 2000 el Protocolo de Cartagena sobre Seguridad de la Biotecnología, que es un acuerdo internacional con el fin de normar sobre la conservación y uso sustentable de la diversidad biológica y la participación en los beneficios que deriven del uso de recursos genéticos (CBD, 2012), acuerdo al que se adhieren múltiples naciones, entre ellas Venezuela.', 'admin@mail.com', 1, 1, '2020-01-20 18:48:44', '2020-01-20 18:52:35'),
(6, '¿Qué es la transgénesis?', 'La biotecnología incluye diversas disciplinas, que incluyen la ingeniería genética: la tecnología que permite tener ADNr (recombinante), es decir, la manipulación deliberada del material genético con diferentes fines (CBUDEC, s.f.)\nDentro de la ingeniería genética existen las técnicas de transgénesis, que implican la introducción de una o más secuencias de ADN de una especie a otra, por medios artificiales (NIH, s.f.). \nCuando se habla de alimentos transgénicos se hace referencia a alimentos provenientes de cultivos vegetales y productos animales, modificados genéticamente (incluyendo el empleo de enzimas y aditivos obtenidos de microorganismos transgénicos en la elaboración y procesamiento de los alimentos), según señala ArgenBio (2007).', 'admin@mail.com', 0, 1, '2020-01-20 19:18:48', '2020-01-20 19:18:48'),
(7, '¿Cuáles son las ventajas para las personas de los OGM?', 'Entre las ventajas que pueden derivar de la manipulación genética de organismos, la FAO (2003) señala que ha permitido ampliar la investigación de enfermedades. Se espera poder aplicar la biotecnología en los procesos de vacunación y producción de medicamentos; mejorar el valor nutritivo de los alimentos y finalmente, la caracterización y posible eliminación de genes alergénicos, son algunos de los potenciales usos de la biotecnología.', 'admin@mail.com', 0, 1, '2020-01-20 19:19:10', '2020-01-20 19:19:10'),
(8, '¿Cuáles son las ventajas para las empresas de los OGM?', 'Entre las ventajas para las empresas, resaltan las relacionadas con la producción agrícola, donde los OGM pueden implicar mayor resistencia a los agentes externos, alimentos básicos más nutritivos y mayor productividad de animales y cultivos, además de mejorar la resistencia y conservación de los productos en los procesos de traslado y almacenamiento. La biotecnología puede proporcionar una mayor productividad por metro cuadrado, disminución de plagas y enfermedades, y una reducción en la necesidad de aplicar sustancias agroquímicas (FAO, 2003).', 'admin@mail.com', 0, 1, '2020-01-20 19:19:31', '2020-01-20 19:19:31'),
(9, '¿Cuáles son los riesgos de los OGM para las personas?', 'Se proponen potenciales efectos negativos del uso de OGM para las personas: la posibilidad de toxicidad para la salud; las posibilidad de provocar reacciones alérgicas; la posibilidad de que los genes insertados sean inestables, con el riesgo de transferencia genética; consecuencias nutricionales asociados con la modificación genética, donde la contaminación de organismos no modificados pueda alterar su seguridad y potencial nutritivo; otros posibles efectos (OEI, s.f.). \nExisten implicaciones sobre el respeto a la libertad de los consumidores son violados con el inadecuado etiquetado de OGM, impidiendo al público conocer el contenido de sus alimentos y decidir si desean o no ingerirlos (Group, 2016). La modificación genética de virus y otros organismos con alta capacidad de mutación y combinación, pueden implicar la aparición de nuevas enfermedades (AgroParlamento, 2001).\nTambién es posible contemplar riesgos económicos para las personas y comunidades, pues los derechos de propiedad intelectual sobre alimentos GM y patentes, tienen impacto sobre los derechos de los agricultores (OEI, s.f.). La acción extrema en la búsqueda del control de los mercados y la protección de sus inversiones, ha hecho que algunas empresas, desarrollen semillas que no pudieran ser reutilizadas o fértiles, (recibiendo el nombre de terminator) que generan dependencia de los campesinos con las transnacionales y así con diversos productos (Massieu, Chauvet, Castañeda, Barajas y González, 2000).', 'admin@mail.com', 0, 1, '2020-01-20 19:20:00', '2020-01-20 19:20:00'),
(10, '¿Cuáles son los riesgos de los OGM para las empresas?a', 'La OEI (s.f.), señala que para las empresas puede haber consecuencias negativas económicas y de relaciones públicas asociadas al uso de OGM. Por lo general, la comercialización de OGM es objeto de extensiva legislación y normas que generan ciertas limitaciones. Igualmente en el caso de los alimentos, existe un valor social/cultural e histórico además del nutricional, incluso connotaciones religiosas, por lo que la modificación tecnológica de los productos puede provocar respuestas negativas entre los consumidores.\nSe ha registrado una tendencia al control del mercado por parte de unas pocas grandes empresas, una creciente homogenización de cultivos, y control de la tecnología por grupos reducidos de capitales, lo que genera monopolios y afecta a los PyMEs. En los últimos años han aumentado las fusiones entre empresas agrobiotecnológicas y semilleras (Massieu, Chauvet, Castañeda, Barajas y González, 2000).', 'admin@mail.com', 0, 1, '2020-01-20 19:20:37', '2020-01-20 19:20:37'),
(11, '¿Cuál es el impacto de los OGM en el medio ambiente?', 'La manipulación de organismos vivos para modificar sus características genéticas es una práctica antigua. Los seres humanos han modificado organismos vivos desde hace aproximadamente 10.000 años. Sin embargo los cambios generados a través de cruces o exposición a mutágenos son imprecisas. Entre los beneficios del uso de OGM, se espera que, con el uso de la biotecnología moderna, aumente la precisión de las modificaciones a animales y cultivos, los cuales son sometidos a mayor grado de pruebas y regulaciones que los productos regulares, aumentando su nivel de seguridad (AgroBio, 2017).\nLa FAO (2003) menciona la posible rehabilitación de tierras degradadas o menos fértiles, la disminución en el uso de agroquímicos y la creación de Biocombustibles a partir de materia orgánica. AgroBio (2017), incluye además la posibilidad de aumentar la agricultura sin labranza, la protección de insectos beneficiosos y una reducción de las emisiones de dióxido de carbono.\nAl mismo tiempo, entre los riesgos ambientales del uso de OGM, resalta de manera principal la disminución de la biodiversidad, la tendencia hacia el monocultivo de variedades puede profundizar la homogeneización cultivos, generando una suerte de erosión genética (Massieu, Chauvet, Castañeda, Barajas y González, 2000). \nEstá demostrada la capacidad de los OGM para dispersarse e introducir genes de ingeniería genética en poblaciones silvestres; la posible persistencia del gen una vez que el OGM ha sido cosechado y la susceptibilidad de los organismos no objetivo como los insectos, bacterias y otros, pudiendo incluso desarrollar organismos resistentes; un mayor uso de sustancias químicas en la agricultura; la tendencia a un menor uso de la rotación de cultivos; el desplazamiento de genes de resistencia a los herbicidas y otros vegetales (OEI, s.f.)', 'admin@mail.com', 1, 1, '2020-01-20 19:21:08', '2020-01-20 20:14:16'),
(12, '¿Cuál es el impacto de los OGM en la economía de un país?', 'Dependiendo de la organización económica de cada país el uso de OGM puede tener impactos positivos o negativos. El uso de OGM es un factor potenciador del desarrollo científico y tecnológico en los países. En cuanto a la productividad agrícola, se ha registrado en varios casos un crecimiento de productividad nacional importante con la incorporación de biotecnología (Bragachini y Manfredi, 2011). \nSin embargo, dependiendo del rol del Estado en éstas prácticas, los desarrollos biotecnológicos tienden a beneficiar más al sector privado y de exportaciones, que a cubrir las necesidades internas alimentarias de la población en los países que los producen. Al mismo tiempo, la biotecnología genera asimetría en las relaciones económicas entre los países, acentuando las brechas entre países industrializados y países en desarrollo, y entre los grandes capitales y las pequeñas empresas dentro de un país (Bota, 2003).', 'admin@mail.com', 0, 1, '2020-01-20 19:21:45', '2020-01-20 19:21:45'),
(13, '¿Qué es la bioética?', 'La bioética es la disciplina que estudia los aspectos éticos implicados en las ciencias de la vida, que incluyen en primer lugar la medicina y la biología, y en segundo lugar las humanidades, abarcando relaciones del hombre con los demás seres vivos y con la salud (PAHO, 2018). La bioética tiene el papel de clarificar las discusiones y debates complejos sobre las consecuencias éticas, sociales, económicas, políticas y jurídicas, etc que se derivan de avances tecnológicos (Rodríguez, 2010).', 'admin@mail.com', 0, 1, '2020-01-20 19:22:07', '2020-01-20 19:22:07'),
(14, '¿Qué es la bioseguridad?', 'La bioseguridad es un conjunto de medidas, protocolos y normas, que aplican en los procedimientos realizados en investigaciones científicas para la prevención de riesgos (biológico, químico, físico) o infecciones, controlando el manejo, uso, almacenamiento y barreras protectoras necesarias para garantizar la seguridad (UDD, s.f.), es decir, es un sistema de normas de acciones de seguridad que orientan y regulan las prácticas en salud (Rosas y Arteaga, 2003).', 'admin@mail.com', 0, 1, '2020-01-20 19:30:37', '2020-01-20 19:30:37'),
(15, '¿Existe una ley de bioseguridad en Venezuela?', 'Venezuela, Panamá y la UNAM de México han elaborado códigos de Bioseguridad y Bioética, introduciendo la regulación ética en las problemáticas de bioseguridad y no circunscribiendo las respuestas sólo a instancias técnicas (Bota, 2003).\nIgualmente, múltiples documentos, reglamentos y leyes en el país abordan el tema de la protección al ambiente, la salud y la sociedad, en cuanto a los riesgos de los OGM. Resalta la Constitución de la República Bolivariana de Venezuela, del año 1999, que alude al tema en sus artículos 11, 110, 127, 129 y 328. Además, documentos con la Ley Orgánica de Ambiente, la Ley Orgánica de Seguridad de la Nación (artículos 11, 13 y 14), la Ley Orgánica de Seguridad y Soberanía Alimentaria (art 12, 17 y 85), la Ley de Gestión de la Diversidad Biológica, a ley de Salud Agrícola Integral (artículo 46), la Ley de Semillas, la Ley sobre Defensas Sanitarias Vegetal y Animal, la Ley de Protección de Fauna Silvestre, el Plan de la Patria, publicado en Gaceta Oficial 6118 del 2013, Ley Orgánica de Ciencia, Tecnología e Innovación y en la Ley de Bosques.', 'admin@mail.com', 0, 1, '2020-01-20 19:33:39', '2020-01-20 19:33:39'),
(16, '¿Cuáles son las instituciones responsables de regular los OGM en Venezuela?', 'Entre los organismos responsables de regular las actividades relacionadas con OGMs en Venezuela, se encuentra los Ministerios con competencia en la materia, como el MINEC – Ministerio del Poder Popular para el Ecosocialismo, MPPS - Ministerio del Poder Popular para la Salud, MPPAPT - Ministerio del Poder Popular para la Agricultura Productiva y Tierras, MPPEUCT - Ministerio del Poder Popular para Educación Universitaria Ciencia, Tecnología, MINPPIBES - Ministerio del Poder Popular de Industrias y Producción Nacional, MPPIC - Ministerio del Poder Popular para Industria y Comercio, MPPPA - Ministerio del Poder Popular de Pesca y Acuicultura, MPPD - Ministro del Poder Popular para la Defensa, MPPEF - Ministerio del Poder Popular de Economía y Finanzas\nIgualmente tienen competencia entes adscritos, incluyendo el INSAI - Instituto Nacional de Salud Agrícola Integral, SENCAMER - Servicio Autónomo Nacional de Normalización, Calidad, Metrología y Reglamentos Técnicos, SENIAT – Servicio Nacional Integrado de Administración Aduanera y Tributaria, y FANB – Fuerza Armada Nacional Bolivariana.', 'admin@mail.com', 0, 1, '2020-01-20 19:34:11', '2020-01-20 19:34:11'),
(17, '¿Por qué es importante el desarrollo de leyes y normas de bioseguridad en Venezuela?', 'Existen múltiples códigos en Venezuela que abordan el tema de los OGM, sin embargo no existe un documento que agrupe y legisle de forma general sobre la materia, con sus respectivos reglamentos específicos. Es importante una unificación de criterios y mantener la normativa actualizada en un campo tecnológico que evoluciona de forma rápida.\nLos desarrollos tecnológicos suelen ser de naturaleza neutra (salvo aquellos creados con el exclusivo propósito de dañar, como las armas), y su alcance depende de quiénes ostentan la propiedad sobre la tecnología y para qué fines la utilizan. Así, la regulación del Estado sobre los OGM, permite controlar que su uso sea, de forma exclusiva, para el beneficio de la población y no para su detrimento. Sólo el desarrollo de leyes y normas permite controlar qué productos entran al territorio, y sus adecuados manejos para evitar los riesgos potenciales a la salud, el ambiente y la economía que se deriven de su uso, previendo que no acarreen consecuencias negativas para la población.', 'admin@mail.com', 0, 1, '2020-01-20 19:34:34', '2020-01-20 19:34:34'),
(18, '¿Cuál es el rol de las personas y las comunidades en el tema de los OGM?', 'Las personas y las comunidades son los principales afectados por el uso de OGM, ya sea que sus consecuencias sean positivas o negativas. Por lo tanto la población tiene derecho a estar informada y tomar decisiones sobre cómo se aplicará dicha tecnología en su país. Venezuela, partiendo del principio de la democracia participativa, integra a las comunidades en los procesos de toma de decisiones a nivel estadal, no sólo en la consulta por el voto, sino desde las discusiones iniciales para la redacción de los documentos normativos. Las personas y comunidades tienen la potestad de proponer leyes y normas, o modificaciones a las existentes, en base a sus saberes y experiencias sobre el tema, y el alcance de su participación puede ser comunal, municipal y nacional (Araque, 2014).', 'admin@mail.com', 1, 1, '2020-01-20 19:35:01', '2020-01-20 19:39:33'),
(19, '1ra. preg. ¿cuando vas a incluir la Encuesta?', NULL, 'salgado.sa.web@gmail.com', 0, NULL, '2020-01-31 19:26:24', '2020-01-31 19:26:24');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `questions`
--
ALTER TABLE `questions`
  ADD PRIMARY KEY (`id`),
  ADD KEY `questions_answered_by_foreign` (`answered_by`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `questions`
--
ALTER TABLE `questions`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=20;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
